abbr -a -- gs 'git status'
abbr -a -- gps 'git push origin'
abbr -a -- gpl 'git pull origin'
abbr -a -- gw 'git switch'
abbr -a -- ga 'git add'
abbr -a -- gc 'git commit'
abbr -a -- t 'tree 1'
abbr -a -- tt 'tree 2'
abbr -a -- ttt 'tree 3'
abbr -a -- gr 'git restore'
abbr -a -- grb 'git rebase'
abbr -a -- gd 'git diff'
abbr -a -- dcu 'docker compose up -d --build --remove-orphans'
abbr -a -- dcd 'docker compose down'
abbr -a -- dcl 'docker compose logs -f'
abbr -a -- dcp 'docker compose ps'
abbr -a -- gsl 'git stash list'
abbr -a -- gsa 'git stash apply stash@{0}'
