abbr -a -- gs 'git status'
abbr -a -- gps 'git push origin'
abbr -a -- gpl 'git pull origin'
abbr -a -- gw 'git switch'
abbr -a -- ga 'git add'
abbr -a -- gc 'git commit'
abbr -a -- t 'tree 1'
abbr -a -- tt 'tree 2'
abbr -a -- ttt 'tree 3'
abbr -a -- gr 'git restore'
