#! /bin/sh

pgrep -x sxhkd -m -1 > /dev/null || sxhkd -m -1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

